appaccount/urls.py
# django.contrib.auth.urls
from django.urls import path, include
from . import views

app_name = 'account'
urlpatterns = [
    path('', include('django.contrib.auth.urls'), name='login'),
    path('logout/', include('django.contrib.auth.urls'), name='logout'),
    path('usuario/<int:pk>', views.account, name='account'),
    path('solicitar/<int:jogador>/<int:time_solicitante>/<int:time_solicitado>/<int:pk>', views.solicitar, name='solicitar'),
    path('confirmacao_solicitar/<int:jogador>/<int:time_solicitante>/<int:time_solicitado>/<int:pk>', views.confirmacao_solicitar, name='confirmacao_solicitar'),
    path('aceitar_transferencia/<int:jogador>/<int:pk>/<int:time_solicitante>/<int:notificacao_id>', views.aceitar_transferencia, name='aceitar_transferencia'),
    path('recusar_transferencia/<int:notificacao_id>/<int:pk>', views.recusar_transferencia, name='recusar_transferencia'),
    path('confirmar_dispensar/<int:pk>/<int:admin>', views.confirmar_dispensar, name='confirmar_dispensar'),
    path('dispensar/<int:pk>/<int:admin>', views.dispensar, name='dispensar'),
]

copao/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('copaoifc.urls')),
    path('times/', include('apptimes.urls')),
    path('transferencias/', include('apptransferencias.urls')),
    path('artilheiros/', include('appartilheiros.urls')),
    path('', include('appaccount.urls')),
]

appaccount/forms.py
from django import forms
from apptimes.models import Usuario
from apptimes.models import Jogador

class LoginForm(forms.Form):
    nome_usuario = forms.CharField(label='Nome Usuário', max_length=100)
    senha = forms.CharField(label='senha', max_length=30)

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        nome_usuario = cleaned_data.get('nome_usuario')
        senha = cleaned_data.get('email')
        if not nome_usuario and not senha:
            raise forms.ValidationError('You have to write something!')

class PartidaForm(forms.Form):
    nome = forms.CharField(label='Nome', max_length=45)
    gols = forms.IntegerField(label='Gols')
    cartao_amarelo = forms.IntegerField(label='Cartão Amarelo')
    cartao_vermelho = forms.IntegerField(label='Cartão Vermelho')

appaccount/views.py
from datetime import date
from itertools import count
from django.contrib.auth import authenticate
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .forms import LoginForm
from apptimes.models import Usuario, Time, Jogador, Notificacao, Transferencia, TransferenciaJogador, JogadorNaPartida, PartidasEditadas, Partida
from django.contrib.auth.models import User
from django.db.models import Q
# Create your views here.

def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data['nome_usuario']
            password = form.cleaned_data['senha']
            user = authenticate(nome_usuario=username, senha=password)
            login(request, user)
    else:
        form = LoginForm()

    return render(request, 'login.html', {'form': form})

def account(request, pk):
    usuario = User.objects.get(id=pk)
    time = Time.objects.get(admin_time=usuario.id)
    times = Time.objects.exclude(id = time.id)

    jogadores = Jogador.objects.filter(id_time=time.id)
    countJ = len(jogadores)
    jogadoresTodos = Jogador.objects.exclude(id_time=time.id).order_by('-id_time')
    notificacoes = Notificacao.objects.filter(id_receptor=pk, respondida=0)

    jogs = []

    notificacoesEnviadas = Notificacao.objects.filter(id_enviador=pk, respondida=0)
    for jog in jogadoresTodos:
        n = 0
        for notE in notificacoesEnviadas:
            if jog.id == notE.id_jogador.id:
                n += 1
        if n == 0:
            if jog.id_time == None:
                timeO = Time(id=0, logo='alow', pontos=0, cor='grey', saldo_gols=0, vitoria=0, admin_time=None)
                jog.id_time = timeO
            jogs.append(jog)

    countT = len(jogs)
    for notI in notificacoes:
        timeAdmin = Time.objects.get(admin_time=notI.id_enviador)
        notI.time = timeAdmin
    countN = len(notificacoes)

    context = {'usuario': usuario, 'time': time, 'jogadoresMeu': jogadores, 'jogadoresTodos': jogs, 'totalJ': countJ, 'totalT': countT, 'times': times, 'notificacoes':notificacoes, 'countN': countN}
    return render(request, 'appaccount/usuario.html', context)

def confirmacao_solicitar(request, jogador, time_solicitante, time_solicitado, pk):
    jogador = Jogador.objects.get(id=jogador)
    if time_solicitado == 0:
        context = {'jogador': jogador, 'time_solicitante': time_solicitante, 'time_solicitado': 0, 'pk': pk}
    else:
        context = {'jogador': jogador, 'time_solicitante': time_solicitante, 'time_solicitado': time_solicitado, 'pk': pk}
    return render(request, 'appaccount/confirma_pedido.html', context)


def solicitar(request, jogador, time_solicitante, time_solicitado, pk):
    if time_solicitado != 0:
        time_solicitante = Time.objects.get(id=time_solicitante)
        jogadoresTimeS = Jogador.objects.filter(id=time_solicitante.id)
        usuario = User.objects.get(id=pk)
        jogador = Jogador.objects.get(id=jogador)
        time_solicitado = Time.objects.get(id=time_solicitado)
        countJogadores = len(jogadoresTimeS)

        if countJogadores >= 13:
            return 'Nao pode solicitar pcausa do numero de jogadores ja cadastrados no time'
        else:
            notificacao = Notificacao.objects.create(id_receptor=time_solicitado.admin_time, id_enviador=time_solicitante.admin_time, id_jogador=jogador)
            return account(request, pk)
    else:
        time_solicitante = Time.objects.get(id=time_solicitante)
        jogadoresTimeS = Jogador.objects.filter(id=time_solicitante.id)
        jogador = Jogador.objects.get(id=jogador)
        countJogadores = len(jogadoresTimeS)

        if countJogadores >= 13:
            return 'Nao pode solicitar pcausa do numero de jogadores ja cadastrados no time'
        else:
            jogador.id_time = time_solicitante
            jogador.save()
            return account(request, pk)

def aceitar_transferencia(request, jogador, pk, time_solicitante, notificacao_id):
    jogador = Jogador.objects.get(id=jogador)
    time_vendedor = jogador.id_time
    time_solicitante = Time.objects.get(id=time_solicitante)
    transferencia = Transferencia.objects.create(time_vendedor=time_vendedor, time_comprador=time_solicitante)
    transferenciaJogador = TransferenciaJogador.objects.create(jogador=jogador, transferencia=transferencia)
    notificacao = Notificacao.objects.get(id=notificacao_id)
    notificacao.respondida = 1
    notificacao.save()

    timeAdminSolicitante = Time.objects.get(admin_time=time_solicitante.admin_time)
    notificacaoDeletar = Notificacao.objects.filter(id_jogador=jogador).exclude(id_enviador=timeAdminSolicitante.admin_time)

    for notDel in notificacaoDeletar:
        notDel.delete()

    jogador.id_time = time_solicitante
    jogador.save()

    partidasDoJogador = JogadorNaPartida.objects.filter(jogador=jogador)

    data = date.today()

    print(data)

    for p in partidasDoJogador:

        if p.partida.data >= data:
            print(p.partida.data)
            p.delete()

    partidasDoTime = Partida.objects.filter(Q(id_time_mandante=time_solicitante) | Q(id_time_visitante=time_solicitante))

    for p in partidasDoTime:
        if p.data > data:
            print(p.data)
            jogador_partida = JogadorNaPartida(jogador=jogador, partida=p, time=jogador.id_time)
            jogador_partida.save()

    return account(request, pk)

def recusar_transferencia(request, notificacao_id, pk):
    notificacao = Notificacao.objects.get(id=notificacao_id)
    notificacao.respondida = 1
    notificacao.save()

    return account(request, pk)

def confirmar_dispensar(request, pk, admin):
    jogador = Jogador.objects.get(id=pk)
    context = {'jogador': jogador, 'admin': admin}
    return render(request, 'appaccount/confirma_dispensar.html', context)

def dispensar(request, pk, admin):
    jogador = Jogador.objects.get(id=pk)
    jogador.id_time = None
    jogador.save()
    return account(request, admin)

appaccount/templates/appaccount/confirma_dispensar.html
{% extends 'base.html' %}
{% block content %}

<div class="ui container">
    <div class="ui centered grid" style="margin-top: 10em">
        <div style="margin-top: 3em; margin-bottom: 3em; height: 10em; width: 40em;" class="ui centered grid">
            <h3>Tem certeza que quer dispensar<text style="color: green"> {{ jogador.nome }}</text>?(Uma vez dispensado não é possível cancelar)</h3>
            <div>
                <a href="{% url 'account:dispensar' pk=jogador.id admin=admin %}"><button class="ui green button">Sim</button></a>
                <a href="{% url 'account:account' pk=admin %}"><button class="ui red button">Não</button></a>
            </div>
        </div>
    </div>
</div>

<article style="margin-top: 23.5em">

</article>




{% endblock %}

appaccount/templates/appaccount/confirma_pedido.html
{% extends 'base.html' %}
{% block content %}

<div class="ui container">
    <div class="ui centered grid" style="margin-top: 10em">
        <div style="margin-top: 3em; margin-bottom: 3em; height: 10em; width: 40em;" class="ui centered grid">
            <h3>Tem certeza que quer contratar<text style="color: green"> {{ jogador.nome }}</text>?(Uma vez feita a solicitação não é possível cancelá-la)</h3>
            <div>
                <a href="{% url 'account:solicitar' jogador=jogador.id time_solicitante=time_solicitante time_solicitado=time_solicitado pk=pk %}"><button class="ui green button">Sim</button></a>
                <a href="{% url 'account:account' pk=pk %}"><button class="ui red button">Não</button></a>
            </div>
        </div>
    </div>
</div>

<article style="margin-top: 23.5em">

</article>
{% endblock %}

appaccount/templates/appaccount/usuario.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div style="margin-top: 5em"></div>

<div class="ui container">
    <div class="ui computer only grid">
        <div class="ui four wide column">
            <div class="ui vertical menu">
                <a id="notS" class="active item">
                    Notificações
                    <div class="ui teal left pointing label">{{ countN }}</div>
                </a>
                <a id="jogS" class="item">
                    Meus Jogadores
                    <div class="ui teal left pointing label">{{ totalJ }}</div>
                </a>
                <a id="transS" class="item">
                    <div class="ui teal left pointing label">{{ totalT }}</div>
                    Transferir
                </a>
            </div>
        </div>
        <div class="twelve wide column">
            <div id="notificacoes" class="ui segment">
                {% for notificacao in notificacoes %}
                <div class="ui three column grid">
                    <div class="eight wide column">
                        <p>
                            <text style="color: blue">{{ notificacao.time }}</text>
                            solicitou
                            <text style="color: green">{{ notificacao.id_jogador }}</text>
                        </p>
                    </div>
                    <div class="four wide right aligned column">
                        <a href="{% url 'account:aceitar_transferencia' jogador=notificacao.id_jogador.id time_solicitante=notificacao.time.id pk=usuario.id notificacao_id=notificacao.id %}"><button class="ui green inverted small button">Aceitar</button></a>
                    </div>
                    <div class="four wide left aligned column">
                        <a href="{% url 'account:recusar_transferencia' notificacao_id=notificacao.id pk=usuario.id%}"><button class="ui red inverted small button">Recusar</button></a>
                    </div>
                </div>
                <div class="ui divider"></div>
                {% endfor %}
            </div>
            <div id="meusJogadores" class="ui segment">
                {% for jogador in jogadoresMeu %}
                <div class="ui two column grid">
                    <div class="twelve wide column"><p>{{ jogador.nome }}</p></div>
                    <div class="four wide right aligned column">
                        <a href="{% url 'account:confirmar_dispensar' pk=jogador.id admin=usuario.id %}"><button class="ui red inverted small button">Dispensar</button></a>
                    </div>
                </div>
                <div class="ui divider"></div>
                {% endfor %}
            </div>

            <div id="todosJogadores" class="ui segment">


                <div class="ui compact menu">
                    <div class="ui simple dropdown item">
                        Times
                        <i class="dropdown icon"></i>
                        <div class="menu">
                            <div class="time_id">
                                <p style="display: none">0</p>
                                <div id="time_dropdown" class="item"><a href="#">Todos</a></div>
                            </div>
                            {% for time in times %}
                            <div class="time_id">
                                <p style="display: none">{{time.id}}</p>
                                <div id="" class="item"><a href="#"><img class="ui mini avatar image" src="{% static 'copaoifc/times/' %}{{ time.logo }}"></a>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>


                <div style="margin: 2.5em"></div>

                {% for jogadorT in jogadoresTodos %}
                <div class="ui three column grid jogador">
                    <alow class="id_time_jogador" style="display: none">{{ jogadorT.id_time.id }}</alow>
                    <div class="six wide column"><p>{{ jogadorT.nome }}</p></div>
                    <div class="six wide column"><p>{% if jogadorT.id_time.id != 0 %}<img class="ui mini image" src="{% static 'copaoifc/times/' %}{{ jogadorT.id_time.logo }}">{% endif %}
                    </p></div>
                    <div class="four wide right aligned column">
                        <a href="{% url 'account:confirmacao_solicitar' jogador=jogadorT.id time_solicitante=time.id time_solicitado=jogadorT.id_time.id pk=usuario.id %}"><button class="ui green inverted small button">Solicitar</button></a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="ui tablet mobile only centered grid">

        <div class="ui horizontal grid">
            <a id="notM" class="ui mini blue button">Notificações - {{ countN }}</a>
            <a id="jogM" class="ui mini button">Meus Jogadores</a>
            <a id="transM" class="ui mini button">Transferências</a>
        </div>


        <div style="margin-top: 3em !important; width: 100%"></div>

        <div id="notificacoesM" class="ui container">
            {% for notificacao in notificacoes %}
            <div class="ui three centered column grid">
                <div class="six wide column">
                    <p>
                        <text style="color: blue">{{ notificacao.time }}</text>
                        solicitou
                        <text style="color: green">{{ notificacao.id_jogador }}</text>
                    </p>
                </div>
                <div class="four wide right aligned column">
                    <a href="{% url 'account:aceitar_transferencia' jogador=notificacao.id_jogador.id time_solicitante=notificacao.time.id pk=usuario.id notificacao_id=notificacao.id %}"><button class="ui green inverted small button">Aceitar</button></a>
                </div>
                <div class="four wide right aligned column">
                    <a href="{% url 'account:recusar_transferencia' notificacao_id=notificacao.id pk=usuario.id%}"><button class="ui red inverted small button">Recusar</button></a>
                </div>
            </div>
            <div class="ui divider"></div>
            {% endfor %}
        </div>
        <div id="meusJogadoresM" class="ui">
            {% for jogador in jogadoresMeu %}

            <div class="ui two column grid">
                <div class="eight wide column"><p>{{ jogador.nome }}</p></div>
                <div class="eight wide right aligned column">
                    <a href="{% url 'account:confirmar_dispensar' pk=jogador.id admin=usuario.id %}"><button class="ui red inverted small button">Dispensar</button></a>
                </div>
            </div>
            {% endfor %}
        </div>

        <div id="todosJogadoresM" class="ui">
            <div class="ui compact menu">
                <div class="ui simple dropdown item">
                    Times
                    <i class="dropdown icon"></i>
                    <div class="menu">
                        <div class="time_id">
                            <p style="display: none">0</p>
                            <div id="time_dropdownM" class="item"><a href="#">Todos</a></div>
                        </div>
                        {% for time in times %}
                        <div class="time_id">
                            <p style="display: none">{{time.id}}</p>
                            <div class="item"><a href="#"><img class="ui mini avatar image" src="{% static 'copaoifc/times/' %}{{ time.logo }}"></a></div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>

            <div style="margin: 2.5em"></div>


            <div style="margin-top: 1.5em"></div>
            <div class="jogadoresTodos">
                {% for jogadorT in jogadoresTodos %}

                <div class="ui three column grid jogador">
                    <alow style="display: none">{{ jogadorT.id_time.id }}</alow>
                    <div class="six wide column"><p>{{ jogadorT.nome }}</p></div>
                    <div class="four wide column"><p>{% if jogadorT.id_time.id != 0 %}<img class="ui mini image" src="{% static 'copaoifc/times/' %}{{ jogadorT.id_time.logo }}">{% endif %}</p></div>
                    <div class="four wide right aligned column">
                        <a href="{% url 'account:confirmacao_solicitar' jogador=jogadorT.id time_solicitante=time.id time_solicitado=jogadorT.id_time.id pk=usuario.id %}"><button class="ui green inverted small button">Solicitar</button></a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>


    </div>
</div>
<div style="margin-bottom: 5em"></div>


<script>
    $(document).ready(function () {

        function editaFooter(){
            if($(window).width() >= 768){
                if (screen.height > $(document).height()){
                    $('#footer').css({"position": "absolute", "bottom": "0", "width": "100%"});
                }
                else {
                    $('#footer').css({"position": "", "bottom": "", "width": ""});
                }
            }
        }

        $('#notificacoes').show();
        $('#meusJogadores').hide();
        $('#todosJogadores').hide();

        $('#notificacoesM').show();
        $('#meusJogadoresM').hide();
        $('#todosJogadoresM').hide();

        $('#notS').click(function () {
            $('#notificacoes').fadeIn();
            $('#meusJogadores').hide();
            $('#todosJogadores').hide();
            $(this).addClass('active');
            $('#jogS').removeClass('active');
            $('#transS').removeClass('active');
            editaFooter();
        });

        $('#jogS').click(function () {
            $('#notificacoes').hide();
            $('#meusJogadores').fadeIn();
            $('#todosJogadores').hide();
            $(this).addClass('active');
            $('#transS').removeClass('active');
            $('#notS').removeClass('active');
            editaFooter();
        });

        $('#transS').click(function () {
            $('#notificacoes').hide();
            $('#meusJogadores').hide();
            $('#todosJogadores').fadeIn();
            $(this).addClass('active');
            $('#jogS').removeClass('active');
            $('#notS').removeClass('active');
            editaFooter();
        });

        $('#notM').click(function () {
            $('#notificacoesM').fadeIn();
            $('#meusJogadoresM').hide();
            $('#todosJogadoresM').hide();
            $(this).addClass('blue');
            $('#jogM').removeClass('blue');
            $('#transM').removeClass('blue');
            editaFooter();
        });

        $('#jogM').click(function () {
            $('#notificacoesM').hide();
            $('#meusJogadoresM').fadeIn();
            $('#todosJogadoresM').hide();
            $(this).addClass('blue');
            $('#transM').removeClass('blue');
            $('#notM').removeClass('blue');
            editaFooter();
        });

        $('#transM').click(function () {
            $('#notificacoesM').hide();
            $('#meusJogadoresM').hide();
            $('#todosJogadoresM').fadeIn();
            $(this).addClass('blue');
            $('#jogM').removeClass('blue');
            $('#notM').removeClass('blue');
            editaFooter();
        });

        $('.time_id').click(function () {
            id_time_filtro = $(this).text();
            id_time_filtro = parseInt(id_time_filtro);

            if (id_time_filtro == 0) {
                $('.jogador').each(function () {
                    $(this).show();
                });
            } else {
                $('.jogador').each(function () {
                    id_time_jogador = $(this).find('alow');
                    id_time_j = id_time_jogador.text();
                    id_time_j = parseInt(id_time_j);

                    if (id_time_filtro == id_time_j) {
                        $(this).show();
                    } else {
                        $(this).hide();
                    }
                });
            }
        })

    })
</script>

{% endblock %}