appadmin/urls.py
from django.urls import path, include
from . import views

app_name = 'adm'
urlpatterns = [
    path('', views.index, name='admin_index'),
    path('editar_partida/<int:pk>/', views.editar_partida, name='editar_partida'),
    path('edita/<int:pk>', views.editar, name='edita'),
    path('cadastrar/', views.cadastrar, name='cadastrar'),
    path('zerar/<int:pk>', views.zerar, name='zerar'),
]

apptimes/urls.py
from django.urls import path, include
from . import views

app_name = 'time'
urlpatterns = [
    path('', views.index, name='times_index'),
    path('time/<int:pk>', views.time, name='time_view'),
]

copao/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('copaoifc.urls')),
    path('times/', include('apptimes.urls')),
    path('transferencias/', include('apptransferencias.urls')),
    path('artilheiros/', include('appartilheiros.urls')),
    path('', include('appaccount.urls')),
]

appadmin/models.py
from django.db import models

# Create your models here.

appadmin/views.py
from datetime import datetime
from itertools import count

from django.shortcuts import render
from apptimes.models import Partida, Time, Jogador, JogadorNaPartida, PartidasEditadas
from django.core.paginator import Paginator
from appaccount.forms import PartidaForm
from django.db.models import Q


# Create your views here.

def index(request):
    partidas = Partida.objects.all().order_by('rodada')

    paginator = Paginator(partidas, 3)  # Show 15 contacts per page

    page = request.GET.get('page')
    contacts = paginator.get_page(page)

    paginas = []

    for numero in range(1, contacts.paginator.num_pages + 1):
        paginas.append(numero)

    context = {'partidas': contacts, 'paginas': paginas}

    return render(request, 'appadmin/admin.html', context)

def editar_partida(request, pk):
    if request.method == 'GET':
        partida = Partida.objects.get(id = pk)
        time1 = Time.objects.get(id=partida.id_time_mandante.id)
        time2 = Time.objects.get(id=partida.id_time_visitante.id)
        jogadores_t1 = Jogador.objects.filter(id_time=time1.id)
        jogadores_t2 = Jogador.objects.filter(id_time=time2.id)

        jogadoresJaEditados = JogadorNaPartida.objects.filter(partida=partida.id)
        jogadoresEditados = []

        jogadoresJaEditados_t1 = []
        jogadoresJaEditados_t2 = []

        jogadoresQueJogaram = []
        for jogador in jogadoresJaEditados:
            jogadoresQueJogaram.append(jogador.jogador)

        for jogador in jogadores_t1:
            if jogador in jogadoresQueJogaram:
                for jogE in jogadoresJaEditados:
                    if jogador.id == jogE.jogador.id:
                        jogadoresEditados.append(jogE)
            # else:
            #     j = JogadorNaPartida(partida=partida, jogador=jogador)
            #     jogadoresEditados.append(j)
            #     j.save()



        for jogador in jogadores_t2:
            if jogador in jogadoresQueJogaram:
                for jogE in jogadoresJaEditados:
                    if jogador == jogE.jogador:
                        jogadoresEditados.append(jogE)
            # else:
            #     j = JogadorNaPartida(partida=partida, jogador=jogador)
            #     jogadoresEditados.append(j)
            #     j.save()

        for jogador in jogadoresEditados:
            if jogador.time.id == time1.id:
                jogadoresJaEditados_t1.append(jogador)
            else:
                jogadoresJaEditados_t2.append(jogador)

        context = {'jogadores_t1': jogadoresJaEditados_t1, 'jogadores_t2': jogadoresJaEditados_t2, 'time1': time1, 'time2': time2, 'jogadorNaPartida': jogadoresEditados, 'partida': partida}
        return render(request, 'appadmin/edita_partida.html', context)

def salvarEditar(request, partida, jogadoresNasPartidas, partidasEditadas, timeA, timeB):
    for p in request.POST:
        if p == 'csrfmiddlewaretoken':
            pass
        elif p[1] == 'o':
            jP = ''
            for num in p:
                if num != 'g' and num != 'o':
                    jP += num

            jogadorP = JogadorNaPartida.objects.get(id=jP)

            ca = 'ca' + jP
            for a in request.POST:
                if a == ca:
                    ca = request.POST[ca]

            go = 'go' + jP
            for a in request.POST:
                if a == go:
                    go = request.POST[go]

            cv = 'cv' + jP
            for a in request.POST:
                if a == cv:
                    cv = request.POST[cv]

            ti = 'ti' + jP
            for a in request.POST:
                if a == ti:
                    ti = request.POST[ti]
                    time = Time.objects.get(id=ti)


            attJogadorP = JogadorNaPartida(id=jP, jogador=jogadorP.jogador, partida=jogadorP.partida, gols=go,
                                           cartoes_amarelos=ca, cartoes_vermelhos=cv, time=time)
            if jogadorP not in jogadoresNasPartidas:
                jogadoresNasPartidas.append(attJogadorP)


    golsTimeA = 0
    golsTimeB = 0

    for jog in jogadoresNasPartidas:
        golsJog = jog.gols
        if jog.time == timeA:
            golsTimeA += int(golsJog)
        else:
            golsTimeB += int(golsJog)

        cartaoA = jog.cartoes_amarelos
        cartaoV = jog.cartoes_vermelhos

        if int(golsJog) > 0:
            jog.jogador.gols += int(golsJog)

        if int(cartaoA) > 0:
            jog.jogador.cartao_amarelo += int(cartaoA)

        if int(cartaoV) > 0:
            jog.jogador.cartao_vermelho += int(cartaoV)

        jog.jogador.save()
        jog.save()

    partida.gols_timeA = golsTimeA
    partida.gols_timeB = golsTimeB

    print(timeA.pontos)

    if golsTimeA > golsTimeB:
        timeA.pontos += 3
        timeA.vitoria += 1
    elif golsTimeB > golsTimeA:
        timeB.pontos += 3
        timeB.vitoria += 1
    else:
        timeA.pontos += 1
        timeB.pontos += 1

    timeA.saldo_gols = timeA.saldo_gols + golsTimeA
    timeA.saldo_gols = timeA.saldo_gols - golsTimeB
    timeB.saldo_gols = timeB.saldo_gols + golsTimeB
    timeB.saldo_gols = timeB.saldo_gols - golsTimeA

    timeA.save()
    timeB.save()

    partida.save()

    partidasEditadas.editada = 1
    partidasEditadas.save()

    return 1

def editar(request, pk):
    partida = Partida.objects.get(id=pk)
    timeA = partida.id_time_mandante
    timeB = partida.id_time_visitante
    partidasEditadas = PartidasEditadas.objects.get(partida = partida)

    jogadoresNasPartidas = []

    if partidasEditadas.editada == 0:
        salvarEditar(request, partida, jogadoresNasPartidas, partidasEditadas, timeA, timeB)
        return render(request, 'appadmin/exibe_partida.html')

    else:
        jogadoresPartidas = JogadorNaPartida.objects.filter(partida = partida)

        golsA = 0
        golsB = 0
        for j in jogadoresPartidas:
            if j.jogador.id_time == partida.id_time_mandante:
                golsA = golsA + j.gols
            else:
                golsB = golsB + j.gols

            j.jogador.gols = j.jogador.gols - j.gols
            j.jogador.cartao_amarelo = j.jogador.cartao_amarelo - j.cartoes_amarelos
            j.jogador.cartao_vermelho = j.jogador.cartao_vermelho - j.cartoes_vermelhos
            j.jogador.save()

            j.gols = 0
            j.cartoes_amarelos = 0
            j.cartoes_vermelhos = 0

            j.save()

        if golsA > golsB:
            partida.id_time_mandante.pontos = partida.id_time_mandante.pontos - 3
            partida.id_time_mandante.vitoria = partida.id_time_mandante.vitoria - 1
        elif golsB > golsA:
            partida.id_time_visitante.pontos = partida.id_time_visitante.pontos - 3
            partida.id_time_visitante.vitoria = partida.id_time_visitante.vitoria - 1
        else:
            partida.id_time_visitante.pontos = partida.id_time_visitante.pontos - 1
            partida.id_time_mandante.pontos = partida.id_time_mandante.pontos - 1

        partida.id_time_mandante.saldo_gols = partida.id_time_mandante.saldo_gols - golsA
        partida.id_time_mandante.saldo_gols = partida.id_time_mandante.saldo_gols + golsB

        partida.id_time_visitante.saldo_gols = partida.id_time_visitante.saldo_gols - golsB
        partida.id_time_visitante.saldo_gols = partida.id_time_visitante.saldo_gols + golsA

        partida.id_time_mandante.save()
        partida.id_time_visitante.save()

        partida.save()

        salvarEditar(request, partida, jogadoresNasPartidas, partidasEditadas, timeA, timeB)

    return render(request, 'appadmin/exibe_partida.html')

def cadastrar(request):
    times = Time.objects.all()

    for time in times:
        jogadores = Jogador.objects.filter(id_time = time)
        partidas = Partida.objects.filter(Q(id_time_mandante=time) | Q(id_time_visitante=time))

        for partida in partidas:
            for jogador in jogadores:
                jogadorNaPartida = JogadorNaPartida.objects.filter(partida = partida, jogador = jogador)

                lista = []
                for j in jogadorNaPartida:
                    lista.append(j)

                if len(lista) > 0:
                    pass
                else:
                    jog = JogadorNaPartida(jogador = jogador, partida = partida, time = jogador.id_time)
                    jog.save()

    partidas = Partida.objects.all()

    for partida in partidas:
        PartidaEditada = PartidasEditadas.objects.filter(partida = partida)
        lista = []
        for p in PartidaEditada:
            lista.append(p)

        if len(lista) > 0:
            pass
        else:
            part = PartidasEditadas(partida = partida)
            part.save()

    return render(request, 'appadmin/exibe_partida.html')

def zerar(request, pk):
    partida = Partida.objects.get(id=pk)

    jaEditada = PartidasEditadas.objects.filter(id=pk, editada=1)

    jaEditadaA = []

    for p in jaEditada:
        jaEditadaA.append(p)

    if len(jaEditadaA) > 0:
        partida.gols_timeA = None
        partida.gols_timeB = None
        partida.save()
    else:
        jogadoresPartidas = JogadorNaPartida.objects.filter(partida=partida)

        golsA = 0
        golsB = 0
        for j in jogadoresPartidas:
            if j.jogador.id_time == partida.id_time_mandante:
                golsA = golsA + j.gols
            else:
                golsB = golsB + j.gols

            j.jogador.gols = j.jogador.gols - j.gols
            j.jogador.cartao_amarelo = j.jogador.cartao_amarelo - j.cartoes_amarelos
            j.jogador.cartao_vermelho = j.jogador.cartao_vermelho - j.cartoes_vermelhos
            j.jogador.save()

        if golsA > golsB:
            partida.id_time_mandante.pontos = partida.id_time_mandante.pontos - 3
            partida.id_time_mandante.vitoria = partida.id_time_mandante.vitoria - 1
        elif golsB > golsA:

appadmin/templates/appadmin/admin.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<style>
    @media (max-width: 723px)
    {
      #botao_editar
       {
        display: none;
       }
    }
    @media (min-width: 724px) {
        #link_editar_mobile
      {
          display: none;
      }
    }
</style>

<div style="margin-top: 5em"></div>


<div class="ui container">

    <div class="ui centered text header">
        <p style="font-size: 3em; font-family: Bitter">Rodada {{ partidas.number }}</p>
    </div>

    <div class="ui container">
        <div class="ui four equal width columns grid">

            <div class="green four wide texto column">Time</div>
            <div class="yellow four wide texto column">Resultado</div>
            <div class="red four wide  texto column">Time</div>
            <div class="grey four wide column">Editar</div>


            {% for partida in partidas %}
            <div class="lightgreen four wide texto column"><p><a href="{% url 'time:time_view' pk=partida.id_time_mandante.id %}"><img class="ui mini avatar image" src="{%  static 'copaoifc/times/'%}{{ partida.id_time_mandante.logo }}" alt=""></a></p></div>
                <div class="lightyellow four wide texto column"><p>{% if partida.gols_timeA == None %} {% else %}{{ partida.gols_timeA }} {%endif%} X {% if partida.gols_timeB == None %} {% else %}{{ partida.gols_timeB }} {% endif %}</p></div>
                <div class="lightred four wide texto column"><p><a href="{% url 'time:time_view' pk=partida.id_time_visitante.id %}"><img class="ui mini avatar image" src="{%  static 'copaoifc/times/'%}{{ partida.id_time_visitante.logo }}" alt=""></a></p></div>
            <div class="lightgrey four wide texto centered column">
                <a href="{% url 'adm:editar_partida' pk=partida.id %}">
                    <button id="botao_editar" class="ui button">Editar</button>
                </a>
                <a id="link_editar_mobile">Editar</a>
            </div>


            {% endfor %}
        </div>
    </div>

     <div style="margin-top: 2em"></div>

                <div class="pagination ui centered grid">
                    <span class="step-links">
                        {% if partidas.has_previous %}
                            <a class="ui mini labeled icon button" href="?page=1"><i class="angle double left icon"></i> 1 </a>
                            <a class="ui small labeled icon blue " href="?page={{ partidas.previous_page_number }}"><i class="left arrow icon"></i>&nbsp;</a>
                        {% endif %}

                        <span class="current" style="font-family: Bitter">
                             {{ partidas.number }}/{{ partidas.paginator.num_pages }}
                        </span>

                        {% if partidas.has_next %}
                            <a style="margin-left: 0.4em" href="?page={{ partidas.next_page_number }}" class="ui mini right labeled bordered icon blue inverted"><i class="right arrow icon"></i>&nbsp;</a>
                            <a href="?page={{ partidas.paginator.num_pages }}" class="ui mini right labeled  icon button"><i class="angle double right icon"></i>{{ partidas.paginator.num_pages }}</a>
                        {% endif %}
                    </span>
                </div>
    <div style="margin-top: 2em"></div>

    <div class="ui centered grid">


        {% for pagina in paginas %}
            <div class="item"><a href="?page={{ pagina }}">{{ pagina }}</a></div>
        {% endfor %}

  </div>
</div>


    <div style="margin-top: 3em" class="ui centered grid">
        <a href="{% url 'adm:cadastrar' %}">
            <button id="cadastrar" class="ui button">Popular Tudo</button>
        </a>
    </div>


    <div style="margin-bottom: 12%"></div>

    </div>

{% endblock %}

appadmin/templates/appadmin/edita_partida.html
{% extends 'base.html' %}
{% block content %}
{% load static %}

<div class="ui container">

        <form style="margin-top: 5em; margin-bottom: 5em" class="ui two column stackable grid" method="post" action="/edita/{{ partida.id }}">
            {% csrf_token %}
            <div class="inverted {{ time1.cor }} column">
                <div style="text-align: center">
                    <div class="ui small image">
                        <img src="{% static 'copaoifc/times/'%}{{ time1.logo }}" alt="">
                    </div>
                </div>
                <div style="margin: 2em"></div>
                <div class="ui grid">
                    <div class="four wide column">Nome</div>
                    <div class="four wide column">G</div>
                    <div class="four wide column">CA</div>
                    <div class="four wide column">CV</div>

                    {% for jogador in jogadores_t1 %}
                        <div class="four wide column">{{ jogador.jogador.nome }}</div>
                        <div class="four wide column"><div class="ui mini input pequenoInput"><input name="go{{ jogador.id }}" value="{{ jogador.gols }}" type="number"></div></div>
                        <div class="four wide column"><div class="ui mini input pequenoInput"><input name="ca{{ jogador.id }}" value="{{ jogador.cartoes_amarelos }}" type="number"></div></div>
                        <div class="four wide column"><div class="ui mini input pequenoInput"><input name="cv{{ jogador.id }}" value="{{ jogador.cartoes_vermelhos }}" type="number">
                                                                                              <input name="ti{{ jogador.id }}" style="display: none" value="{{ jogador.time.id }}"></div></div>
                    {% endfor %}
                </div>
            </div>
            <div class="inverted {{ time2.cor }} column">
                <div style="text-align: center">
                    <div class="ui small image">
                        <img src="{% static 'copaoifc/times/'%}{{ time2.logo }}" alt="">
                    </div>
                </div>
                <div style="margin: 2em"></div>
                 <div class="ui grid">
                     <div class="four wide column">Nome</div>
                     <div class="four wide column">G</div>
                     <div class="four wide column">CA</div>
                     <div class="four wide column">CV</div>

                     {% for jogador in jogadores_t2 %}
                        <div class="four wide column">{{ jogador.jogador.nome }}</div>
                        <div class="four wide column"><div class="ui mini input pequenoInput"><input name="go{{ jogador.id }}" value="{{ jogador.gols }}" type="number"></div></div>
                        <div class="four wide column"><div class="ui mini input pequenoInput"><input name="ca{{ jogador.id }}" value="{{ jogador.cartoes_amarelos }}" type="number"></div></div>
                        <div class="four wide column"><div class="ui mini input pequenoInput"><input name="cv{{ jogador.id }}" value="{{ jogador.cartoes_vermelhos }}" type="number">
                                                                                              <input name="ti{{ jogador.id }}" style="display: none" value="{{ jogador.time.id }}"></div></div>
                     {% endfor %}
                </div>
            </div>
            <div class="ui centered grid">
                <div class="ui sixteen wide column">
                    <button style="margin: 1em" class="ui green button" type="submit">Enviar</button>
                </div>
            </div>
        </form>

        <div style="margin-bottom: 2em" class="ui centered grid">
            <a href="{% url 'adm:zerar' pk=partida.id %}">
                <button class="ui tiny button">Anular Atribuições</button>
            </a>
        </div>

</div>

{% endblock %}

appadmin/templates/appadmin/exibe_partida.html
{% extends 'base.html' %}
{% block content %}

<form id="form" action="/adm/" method="get"></form>

<script>
    $('#form').submit()
</script>

{% endblock %}