appaccount/urls.py
# django.contrib.auth.urls
from django.urls import path, include
from . import views

app_name = 'account'
urlpatterns = [
    path('', include('django.contrib.auth.urls'), name='login'),
    path('logout/', include('django.contrib.auth.urls'), name='logout'),
    path('usuario/<int:pk>', views.account, name='account'),
    path('solicitar/<int:jogador>/<int:time_solicitante>/<int:time_solicitado>/<int:pk>', views.solicitar, name='solicitar'),
    path('confirmacao_solicitar/<int:jogador>/<int:time_solicitante>/<int:time_solicitado>/<int:pk>', views.confirmacao_solicitar, name='confirmacao_solicitar'),
    path('aceitar_transferencia/<int:jogador>/<int:pk>/<int:time_solicitante>/<int:notificacao_id>', views.aceitar_transferencia, name='aceitar_transferencia'),
    path('recusar_transferencia/<int:notificacao_id>/<int:pk>', views.recusar_transferencia, name='recusar_transferencia'),
    path('confirmar_dispensar/<int:pk>/<int:admin>', views.confirmar_dispensar, name='confirmar_dispensar'),
    path('dispensar/<int:pk>/<int:admin>', views.dispensar, name='dispensar'),
]

appadmin/urls.py
from django.urls import path, include
from . import views

app_name = 'adm'
urlpatterns = [
    path('', views.index, name='admin_index'),
    path('editar_partida/<int:pk>/', views.editar_partida, name='editar_partida'),
    path('edita/<int:pk>', views.editar, name='edita'),
    path('cadastrar/', views.cadastrar, name='cadastrar'),
    path('zerar/<int:pk>', views.zerar, name='zerar'),
]

appartilheiros/urls.py
from django.urls import path, include
from . import views

app_name = 'artilheiros'
urlpatterns = [
    path('', views.index, name='artilheiros_index'),
]

apppartidas/urls.py
from django.urls import path, include
from . import views

app_name = 'partidas'
urlpatterns = [
    path('', views.index, name='partidas_index'),
]

copao/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('copaoifc.urls')),
    path('times/', include('apptimes.urls')),
    path('transferencias/', include('apptransferencias.urls')),
    path('artilheiros/', include('appartilheiros.urls')),
    path('', include('appaccount.urls')),
]

copaoifc/urls.py
from django.urls import path, include
from . import views
from apptimes import views as times
from apptimes import urls as time
from appclassificacao import urls as classificacao
from appartilheiros import urls as artilheiros
from apppartidas import urls as partidas
from apptransferencias import urls as transferencias
from appaccount import urls as login
from appadmin import urls as admin


urlpatterns = [
    path('', views.index, name='index'),
    path('times/', times.index , name='times'),
    path('', include(time, namespace='time')),
    path('classificacao/', include(classificacao, namespace='classificacao')),
    path('artilheiros/', include(artilheiros, namespace='artilheiros')),
    path('partidas/', include(partidas, namespace='partidas')),
    path('transferencias/', include(transferencias, namespace='transferencias')),
    path('', include(login, namespace='login')),
    path('', include(admin, namespace='edita')),
    path('adm/', include(admin, namespace='adm'))

]

copaoifc/models.py
from django.db import models

copaoifc/views.py
from django.shortcuts import render
from apptimes.models import Time


app_name = 'index'
def index(request):
    times = Time.objects.all()
    context = {'name': 'Index', 'times': times}
    return render(request, 'copaoifc/index.html', context)

def login(request):
    context = {'name' : 'Login'}
    return render(request, 'copaoifc/index.html', context)

copaoifc/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=2, user-scalable=no"/>
    {% load static %}
    {% block title %}
    <title>Copão IFC</title>
    {% endblock %}

    <link rel="stylesheet" href="{% static 'semantic-2.4.1/semantic.min.css' %}" type="text/css"/>
    <link href="https://fonts.googleapis.com/css?family=Bitter:700" rel="stylesheet">

    <script src="{% static 'jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'semantic-2.4.1/semantic.min.js' %}"></script>
    <style type="text/css">


        .ui.inverted.menu {
            border-radius: 0;
            flex-wrap: wrap;
            border: none;
            padding-left: 0;
            padding-right: 0;
        }

        .ui.mobile.only.grid .ui.menu .ui.vertical.menu {
            display: none;
        }

        .item {
            font-family: 'Bitter', serif;

        }

        .column {
            font-family: 'Bitter', serif;
        }


        .texto {
            text-align: center !important;
        }

        .lightgreen {
            background-color: #A7FFB2;
        }

        .lightgrey {
            background-color: #C1BFC4;
        }

        .lightyellow {
            background-color: #E0D994;
        }

        .lightred {
            background-color: #E58C8C;
        }

        .pequeno {
            height: 4em;
        }

        .pequenoInput{
            width: 5em;
        }


        p {
            /*text-align: center;*/
            position: relative;
            top: 50%;
            -ms-transform: translateY(-50%);
            -webkit-transform: translateY(-50%);
            transform: translateY(-50%);
        }

        @media only screen and (max-width: 722px) {
            .trans_mobile{
                font-size: 0.8em;
            }


        }

        @media only screen and (min-width: 722px) {
            /*.formLogin {*/
                /*width: 30%;*/
            /*}*/

            .loginForm{
                padding: 2em 30%;
            }
        }

        .loginForm{
                padding-top: 2em;
            }

    </style>
</head>

<body>

<!-- Menu -->

<body>
{% block menu %}

<div id="menu" class="ui computer only padded grid">
    <div class="ui green borderless fluid huge inverted menu" style="border-radius: 0.25em">
        <div class="menu" style="margin-left: 2.5em">
            {% load static %}
            <a class="header item" href="{% url 'index' %}"><img class="ui mini avatar image"
                                                                 src="{% static 'copaoifc/logo.jpg' %}" alt=""></a>
            <a class="item" href="{% url 'index' %}">Home</a>
            <a href="{% url 'classificacao:classificacao_index' %}" class="item">Classificação</a>
            <a href="{% url 'artilheiros:artilheiros_index' %}" class="item">Artilheiros</a>
            <a href="{% url 'partidas:partidas_index' %}" class="item">Partidas</a>
            <a href="{% url 'transferencias:transferencias_index' %}" class="item">Transferências</a>
        </div>
        <div class="right menu">
            <div class="item">
                {% if user.is_authenticated == False%}
                <a href="{% url 'account:login' %}" class="ui white inverted button">Login</a>
                {% else %}
                    {% if user.id == 1 %}
                    <a href="{% url 'adm:admin_index' %}" class="ui white inverted button">{{user.username}}</a>
                    {% else %}
                    <a href="{% url 'account:account' pk=user.id %}" class="ui white inverted button">{{user.username}}</a>
                    {% endif %}
                <div style="margin: 0.3em"></div>
                <a href="{% url 'account:logout' %}" class="ui white inverted button">Logout</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>


<div class="ui mobile tablet only padded grid">
    <div class="ui green borderless fluid huge inverted menu">
        {% load static %}
        <a class="header item" href="{% url 'index' %}"><img class="ui mini avatar image"
                                                             src="{% static 'copaoifc/logo.jpg' %}" alt=""></a>
        <div class="right menu">
            <div class="item">
                <button class="ui icon toggle basic inverted button">
                    <i class="content icon"></i>
                </button>
            </div>
        </div>
        <div class="ui green vertical borderless fluid inverted menu">
            <a class="item" href="{% url 'index' %}">Home</a>
            <a href="{% url 'classificacao:classificacao_index' %}" class="item">Classificação</a>
            <a href="{% url 'artilheiros:artilheiros_index' %}" class="item">Artilheiros</a>
            <a href="{% url 'partidas:partidas_index' %}" class="item">Partidas</a>
            <a href="{% url 'transferencias:transferencias_index' %}" class="item">Transferências</a>
            <div class="item">
                {% if user.is_authenticated == False%}
                <a href="{% url 'account:login' %}" class="ui white inverted button">Login</a>
                {% else %}
                <a href="{% url 'account:account' pk=user.id %}" class="ui white inverted button">{{user.username}}</a>
                <a href="{% url 'account:logout' %}" class="ui white inverted button">Logout</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}

{% endblock %}

<!-- Footer -->
{% block footer %}
<div id="footer" class="ui green inverted vertical fixed footer segment" style="border-radius: 0.25em">
    <div class="ui inverted equal height stackable centered grid">
        <div class="row" style="margin-top: 0.2em">
            <div style="padding: 0.2em">
                <button id="insta" class="ui instagram button">
                    <i class="instagram icon"></i>
                    Instagram
                </button>
            </div>
            <div style="padding: 0.2em">
                <button id="youtube" class="ui youtube button">
                    <i class="youtube icon"></i>
                    Youtube
                </button>
            </div>
            <div style="padding: 0.2em">
                <button id="twitter" class="ui twitter button">
                    <i class="twitter icon"></i>
                    Twitter
                </button>
            </div>
        </div>
    </div>
    <div class="ui inverted equal height centered grid">
        <div class="eight wide right aligned column">
            <div class="ui tiny image">
                <a href="http://ifc.edu.br/"><img src="{% static 'copaoifc/logo-ifc-vertical-branco.png' %}" alt=""></a>
            </div>
        </div>
        <div class="eight wide left aligned column">
            <div class="ui tiny image">
                <a href="http://fabricadesoftware.ifc.edu.br/"><img src="{% static 'copaoifc/logo-fabrica.png' %}" alt=""></a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script id="script">
    $(document).ready(function () {
        $(".ui.toggle.button").click(function () {
            $(".mobile.only.grid .ui.vertical.menu").toggle(250);
        });

        $('#youtube').click(function () {
            window.open("https://www.youtube.com/channel/UCLn3EBtAY09Mb-JGLyCu1aw");
        });

        $('#insta').click(function () {
            window.open("https://www.instagram.com/copao_ifc/?hl=pt");
        });

        $('#twitter').click(function () {
            window.open("https://twitter.com/copaoifc");
        });

        $('.ui.sidebar')
            .sidebar('toggle');

        $('.ui.labeled.icon.sidebar')
            .sidebar('toggle');

        if($(window).width() >= 768){
            if (screen.height > $(document).height()){
                $('#footer').css({"position": "absolute", "bottom": "0", "width": "100%"});
            }
            else {
                $('#footer').css({"position": "", "bottom": "", "width": ""});
            }
        }

        $(window).resize(function () {
            if($(window).width() >= 768){
                if (screen.height > $(document).height()){
                    $('#footer').css({"position": "absolute", "bottom": "0", "width": "100%"});
                }
            }
        });
    })

</script>
{% endblock %}
{% block script2 %}
{% endblock %}
</body>